// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum Enum_DistanceUnit
{
	KILOMETER("c883799c-7410-46ae-9579-31844dc152cc"),
	STATUTE_MILE("087896fe-3317-40a1-8767-592709f44f53"),
	NAUTICAL_MILE("6e4656a6-7a54-4b20-ab18-149227902110");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_DistanceUnit(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
