// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum GeocodingProvider
{
	Google("5a33be16-f5f6-488d-8708-5961095610a2"),
	Geocodio("2512c9c5-7b3e-46c8-8079-1632271cb01b"),
	LocationIQ("7a6271b0-37e7-4f2b-bb50-59bcecaf8895"),
	MapQuest("4d980ba1-4c91-471a-9586-a2ec409b8ca9");

	private final java.lang.String i18nCaptionKey;
	
	private GeocodingProvider(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
