// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum GeocodingProvider
{
	Google("8cd0587f-ae77-4eab-9a7b-1329421e9e8f"),
	Geocodio("14b7fd82-6b91-4921-b8f0-3a6d2aadf050"),
	LocationIQ("ecad51e3-47f2-49f5-829e-4ba61b5f6096"),
	MapQuest("b5656156-57cf-4e70-8fe7-85c3e34d52e5");

	private final java.lang.String i18nCaptionKey;
	
	private GeocodingProvider(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
