// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum GeocodingProvider
{
	Google("c21699af-503f-496c-8ddb-c8c87fe704ea"),
	Geocodio("1da3e73e-b6a0-4c7b-812e-19e6247b49c4"),
	LocationIQ("6d23d53b-33fe-4ea7-bbbf-16d67185eb2f"),
	MapQuest("9fce8fd4-8960-45c6-8a23-e43104b38362");

	private final java.lang.String i18nCaptionKey;
	
	private GeocodingProvider(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
