// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum Platform
{
	Web("6893fff5-9191-42c0-a655-da57aee483d8"),
	Native_mobile("28b1888f-56f8-4bba-9bab-dd6db10a99cb"),
	Hybrid_mobile("798efb06-e7b0-4a12-87a5-ecc8b752dd87");

	private final java.lang.String i18nCaptionKey;
	
	private Platform(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
