// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("b4aaa953-5b94-42d4-ab09-83b0fa98f67a"),
	startsWith("2876a142-c415-4293-b6c1-6cb7daf46e73"),
	endsWith("4646aeb2-7f97-4dbe-ac7d-af29709fe367"),
	between("5a805625-9231-422f-9d9e-6e188c77cf68"),
	greater("e5311d0f-75fc-43c1-8e11-f25b412747a5"),
	greaterEqual("6f5c3644-26d0-4be3-93a7-f04c9b769d59"),
	equal("c09cdbfb-97be-4760-babb-5b496686ece1"),
	notEqual("cb8d5b9f-8dcf-4ca6-b825-308f0e974b44"),
	smaller("7dcf86c5-c5be-4420-934a-e31a2d72792f"),
	smallerEqual("4184da85-aa93-4c46-9c7c-13577e240e1e"),
	empty("cea9ef15-227e-4a4c-ab70-018df25e5113"),
	notEmpty("8e6105be-6de5-4e1b-8a88-d62330bae90a");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
