// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package datawidgets.proxies;

public enum Filter_Operators
{
	contains("afd91934-0db1-435f-a212-96ca197f3460"),
	startsWith("8e614009-358c-4b6d-8157-6618b4189060"),
	endsWith("69268b6d-2b58-4879-9101-d31ba3f87609"),
	between("d55f3904-5ef9-4973-8b27-e47d83b71d32"),
	greater("f98f0c39-90f3-45f9-ad31-d71ad5a4c543"),
	greaterEqual("02d5426b-1cb5-4cdb-a169-082a1161c505"),
	equal("81008e9c-17cb-43fc-b777-88611ed82ab2"),
	notEqual("c31ac7f1-6fc1-4e68-aa56-cb8e44cb1f5a"),
	smaller("7ad415a5-66fb-4ed8-9eb0-1aef0ed2b4a5"),
	smallerEqual("e49b53e8-4085-474f-90e3-c654ebad0b36"),
	empty("929e930c-2c85-4ec6-b1d3-57626cfc6f41"),
	notEmpty("12c44f5d-e70c-4b9d-8a71-c339b7c07f80");

	private final java.lang.String i18nCaptionKey;
	
	private Filter_Operators(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
