// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum Enum_PermissionStatus
{
	unavailable("c8212d51-6270-4162-b829-11f9fa3789b3"),
	denied("4fbe705b-b4d6-43d9-9131-608975f3847f"),
	limited("dd5c76fb-a35d-4e5f-be70-341483ccdb7f"),
	granted("ae5e270e-e741-4734-8b32-2467dc399c65"),
	blocked("7b1f1e48-1864-43c5-95a0-f43c5625e0e6");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_PermissionStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
