// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum Enum_PermissionStatus
{
	unavailable("26f4d9e0-09b7-48be-b77b-8456c0dc549b"),
	denied("dd2afd72-40d6-4fa9-b9e9-9cdf9b491326"),
	limited("bca5e343-1e1e-4296-b7f9-6dc327cdbb00"),
	granted("0760447d-cd8e-4643-ac6d-61c8100eb06b"),
	blocked("437004f3-0f5c-4205-bee4-98962f9e0e0b");

	private final java.lang.String i18nCaptionKey;
	
	private Enum_PermissionStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
