// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum InAppBrowserDismissButtonStyle
{
	done("b1237300-0c14-45b0-84b7-799f7766deaa"),
	close("fb40bcb6-5e96-4f66-a39f-772d36a972cb"),
	cancel("9e18d5ce-22f1-4e9b-890a-46c064861ee8");

	private final java.lang.String i18nCaptionKey;
	
	private InAppBrowserDismissButtonStyle(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
