// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum PictureQuality
{
	original("7d7aa32f-cdd5-4ae7-a94c-1b8efabf9aef"),
	low("eb6aaf77-6253-4e69-b857-238dd64bcd9d"),
	medium("a8a02903-1072-46a5-90d7-fda49f2b7c3f"),
	high("7a032e62-4207-4de8-a2d4-27047ba24478"),
	custom("070c36f7-456f-4946-b2a7-e6241550604d");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
