// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum PictureQuality
{
	original("5618661e-f63e-43ee-9af2-4662c31928c0"),
	low("8f5bb146-d805-4a55-828c-0b50ed08a16e"),
	medium("91345a65-ad59-46d7-9701-25e15617656c"),
	high("971dce72-60ea-4a3a-bfaf-0f855b5c36b7"),
	custom("4514f245-d618-4fd6-9f5b-c42f09647286");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
