// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum PictureQuality
{
	original("a02de70f-7dd1-4fb2-94ce-f79164d930e7"),
	low("904ac7e6-c64c-4ba0-8264-3e2ad73852d9"),
	medium("f1f177ce-12c0-4bab-85c5-8e7a47773ada"),
	high("414fe378-9763-4ad9-b0a3-1de129fc659e"),
	custom("12d53f24-6e4e-41db-a4d5-84c948011db6");

	private final java.lang.String i18nCaptionKey;
	
	private PictureQuality(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
