// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nativemobileresources.proxies;

public enum StatusBarStyle
{
	DefaultStyle("a81e0eb2-e77a-4965-beb2-212749c8b8ef"),
	LightContentStyle("c8c617a1-158f-42f5-80f5-02a09a3153d1"),
	DarkContentStyle("372aaf14-5046-4d8d-bbaa-a52af77c2703");

	private final java.lang.String i18nCaptionKey;
	
	private StatusBarStyle(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
